### PR TITLE
Complete header section

### PR DESCRIPTION
**Pull request by Whefert**
Created header section on site

### CODE REVIEW

**Comment by stephdavid** [comment]
Too many divs. Needs to be more semantic – i.e. use main and many sections, use an aside for previous searches
No CAPS – it’s shouting, and not accessible
No nav is required
Needs headers semantically structured – h1, h2, h3, in this there is no h1 or h2s
I suggest to have the name of the app as an h1, Definition, Pronunciation, (Examples) and Previous Searches as h2, with Example1, 2 and 3 as h3
I’m not sure what the Examples section means

The input element requires a visible label i.e. “Search a word” as well as placeholder text.

**Comment by HillaryM17** [comment]
I really like what you've done so far. 
The only comments I have are that the pronunciation div shouldn't be within the definition div, they should have their own designated sections. 
Then stylistically, I think all three headers should be aligned on the left and the capital text for the title should be a nice logo or font, don't know if we need to decide on a name first to do this?

**Comment by mattlusty** [comment]
Good work on this feature! 
Its functioning correctly!
Looks descent!

Just my minor critiques, but I would not worry about them for this project, but...

Non-critical HTML Code Improvement
Index.html (Line 39)
Looks like there are 2 Bootstrap js files (is one a duplicate?)

Non-critical HTML Code Improvement
Element (.nav a)
position: absolute
This takes the element out of the flow of the page. May cause layout issues later.

Non-critical HTML Code Improvement
Search icon and input elements are nested within a div (.col) within a div (.row)
I would suggest you don’t need any of these bootstrap rows or cols (instead just one single div to contain the icon and input elements.

**Review by HillaryM17 — APPROVED** [review]
The capital text for the title should be a nice logo or font, don't know if we need to decide on a name first to do this?

**Pull request merged**
